apiVersion: v1
kind: Service
metadata:
  name: svc-calculator-server
  labels:
    app: svc-calculator-server
spec:
  type: LoadBalancer
  selector:
    app: calculator-server
  ports:
  - name: http
    protocol: TCP
    port: 8085
    targetPort: 8080
